# 持续部署苏康码,自动发送邮件

name: CD

# 发生repository_dispatch时执行
on: repository_dispatch

# 工作
# 检出项目
# 获取base64编码
# 写入到本地图片文件
# 使用nodejs读取图片文件
# 使用nodejs合成图片
# 合成图片写到本地文件
# 使用邮箱发送本地合成好的文件
#
jobs:
  # This workflow contains a single job called "base"
  base:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 检出项目
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 获取base64编码  ${{ github.event.client_payload.pics }}
      - name: base64tofile
        uses: RollyPeres/base64-to-path@v1
        with:
          filePath: ${{ github.workspace }}/${{ github.event.client_payload.filename }}
          encodedString: ${{ github.event.client_payload.pic }}
      # 发送邮件
      - name: Send email
        uses: devellany/send-mail@v1.0.2
        with:
          # 已经验证可以发送  太难了  from和account要设置一致 最好自己发给自己
          host: smtp.sohu.com
          # Optional port (defaults to 465)
          port: 25
          account: 1259154099287736320@sohu.com
          password:  ${{ secrets.sohu_mail_password }}
          sender: 1259154099287736320@sohu.com
          from: 1259154099287736320@sohu.com
          to: 1259154099287736320@sohu.com
          subject: 测试主题
          body: 正文内容
          # Optional content type (defaults to text/plain)
          contentType: text/plain
          # Optional attachment files (JSON type. require property 'path')
          #          attachments: '[{"path":"${{ steps.write_file.outputs.filePath }}"}]'
          attachments: '[{"path":"${{ github.workspace }}/${{ github.event.client_payload.filename }}"}]'