# 持续部署苏康码,自动发送邮件

name: CD

# 发生repository_dispatch时执行
on: repository_dispatch

# 工作
# 检出项目
# 获取base64编码
# 写入到本地图片文件
# 使用nodejs读取图片文件
# 使用nodejs合成图片
# 合成图片写到本地文件
# 使用邮箱发送本地合成好的文件
#
jobs:
  # This workflow contains a single job called "base"
  base:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 检出项目
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # 获取base64编码  ${{ github.event.client_payload.pics }}
      - name: base64tofile
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: '1.png'
          encodedString: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/PjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+PHN2ZyB0PSIxNTg5MDM2MzExNjMyIiBjbGFzcz0iaWNvbiIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHAtaWQ9IjIxODgiIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCI+PGRlZnM+PHN0eWxlIHR5cGU9InRleHQvY3NzIj48L3N0eWxlPjwvZGVmcz48cGF0aCBkPSJNNTEyIDYwOGE5NiA5NiAwIDEgMSAwLTE5MiA5NiA5NiAwIDAgMSAwIDE5Mm0wLTI1NmMtODguMjI0IDAtMTYwIDcxLjc3Ni0xNjAgMTYwczcxLjc3NiAxNjAgMTYwIDE2MCAxNjAtNzEuNzc2IDE2MC0xNjAtNzEuNzc2LTE2MC0xNjAtMTYwIiBmaWxsPSIjZDgxZTA2IiBwLWlkPSIyMTg5Ij48L3BhdGg+PHBhdGggZD0iTTUxMiA4MDBjLTIxMi4wNjQgMC0zODQtMjU2LTM4NC0yODhzMTcxLjkzNi0yODggMzg0LTI4OCAzODQgMjU2IDM4NCAyODgtMTcxLjkzNiAyODgtMzg0IDI4OG0wLTY0MEMyNjUuMjQ4IDE2MCA2NCA0NDMuMDA4IDY0IDUxMmMwIDY4Ljk5MiAyMDEuMjQ4IDM1MiA0NDggMzUyczQ0OC0yODMuMDA4IDQ0OC0zNTJjMC02OC45OTItMjAxLjI0OC0zNTItNDQ4LTM1MiIgZmlsbD0iI2Q4MWUwNiIgcC1pZD0iMjE5MCI+PC9wYXRoPjwvc3ZnPg==

      # 发送邮件
      - name: Send email
        uses: devellany/send-mail@v1.0.2
        with:
          # 已经验证可以发送  太难了  from和account要设置一致
          host: smtp.yandex.com
          # Optional port (defaults to 465)
          port: 465
          account: miaozilong31@yandex.com
          password: m7269535
          sender: miaozilong31@yandex.com
          from: miaozilong31@yandex.com
          to: miao.zilong@qq.com
          subject: 测试主题
          body: 正文内容
          # Optional content type (defaults to text/plain)
          contentType: text/plain
          # Optional attachment files (JSON type. require property 'path')
          attachments: '[{"path":"1.png"}]'